# Generated by Django 5.0.6 on 2025-04-03 17:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoupload",
            name="video",
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
